[buildPlans.iosevka-sandvich]
family = "Iosevka Sandvich"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-sandvich.variants]
  inherits = "ss14"

    [buildPlans.iosevka-sandvich.variants.design]
    a = "single-storey-earless-corner-tailed"
    b = "toothless-corner"
    d = "toothless-corner-serifless"
    f = "flat-hook"
    g = "earless-corner"
    i = "serifed-flat-tailed"
    m = "short-leg"
    n = "earless-corner-straight"
    p = "earless-corner"
    q = "earless-corner"
    r = "earless-corner"
    w = "straight"
    y = "cursive"
    long-s = "flat-hook-tailed"
    eszet = "sulzbacher-tailed"
    lower-alpha = "crossing"
    cyrl-ya = "curly"
    seven = "straight-serifless"
    dollar = "open"
    cent = "open"
    lig-ltgteq = "flat"

  [buildPlans.iosevka-sandvich.ligations]
  inherits = "dlig"
